use crate::day8::Day8;
use crate::solution::Solution;

static SAMPLE: &str = r#"
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"#;

#[test]
fn test_part1() {
    let day = Day8 {};
    assert_eq!(day.solve_part1(SAMPLE), "14");
}

#[test]
fn test_part2() {
    let day = Day8 {};
    assert_eq!(day.solve_part2(SAMPLE), "34");
}
